import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {deflateSync} from 'node:zlib';
import {readFile} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import {before,after,test} from 'node:test';
import {build} from 'esbuild';
import {Miniflare,convertV4MiniflareOptions} from 'miniflare';
const origin='https://cms.test',session='a'.repeat(64),csrf='b'.repeat(64),mediaId='11111111-1111-4111-8111-111111111111';
const hash=b=>createHash('sha256').update(b).digest('hex');let mf,db,bucket;
function crc(b){let c=0xffffffff;for(const v of b){c^=v;for(let i=0;i<8;i++)c=(c>>>1)^((c&1)?0xedb88320:0);}return(c^0xffffffff)>>>0;}
function chunk(t,b){const len=Buffer.alloc(4),sum=Buffer.alloc(4),body=Buffer.concat([Buffer.from(t),b]);len.writeUInt32BE(b.length);sum.writeUInt32BE(crc(body));return Buffer.concat([len,body,sum]);}
function paeth(a,b,c){const p=a+b-c,x=Math.abs(p-a),y=Math.abs(p-b),z=Math.abs(p-c);return x<=y&&x<=z?a:y<=z?b:c;}
function png({opaque=false,empty=false,filter=0,expansion=false,width=32,height=32}={}){const head=Buffer.alloc(13);head.writeUInt32BE(width);head.writeUInt32BE(height,4);head[8]=8;head[9]=6;const rows=[];let prev=Buffer.alloc(width*4);for(let y=0;y<height;y++){const raw=Buffer.alloc(width*4);for(let x=0;x<width;x++){raw[x*4]=90;raw[x*4+1]=170;raw[x*4+2]=30;raw[x*4+3]=empty?0:opaque?255:(x>7&&x<24&&y>7&&y<24?255:0);}const row=Buffer.from(raw);for(let x=0;x<row.length;x++){const a=x>=4?raw[x-4]:0,b=prev[x],c=x>=4?prev[x-4]:0,p=filter===0?0:filter===1?a:filter===2?b:filter===3?Math.floor((a+b)/2):paeth(a,b,c);row[x]=(raw[x]-p)&255;}rows.push(Buffer.concat([Buffer.from([filter]),row]));prev=raw;}const pixels=Buffer.concat(rows),compressed=deflateSync(expansion?Buffer.concat([pixels,Buffer.alloc(1000)]):pixels);return Buffer.concat([Buffer.from([137,80,78,71,13,10,26,10]),chunk('IHDR',head),chunk('IDAT',compressed),chunk('IEND',Buffer.alloc(0))]);}
const seed=()=>({schemaVersion:1,revision:0,profile:{name:'Fixture Owner'},projects:[{id:1,slug:'owned-model',title:'Owned model',nsfw:false,full:`/media/${mediaId}/original`,heroWebp:`/media/${mediaId}/original`,thumbWebp:`/media/${mediaId}/preview`},{id:2,slug:'legacy',title:'Legacy',nsfw:false,full:'/assets/full.webp',thumbWebp:'/assets/transparent.webp'}],editorial:[],sketches:[]});
const ownerHeaders=()=>({Cookie:`__Host-ashvini-cms=${session}`,Origin:origin,'X-CSRF-Token':csrf});
const bearer=d=>({Authorization:`Bearer ${d.token}`});
const req=(path,method='GET',body,headers={})=>mf.dispatchFetch(origin+path,{method,headers:{...(body!==undefined?{'Content-Type':'application/json'}:{}),...headers},...(body!==undefined?{body:JSON.stringify(body)}:{})});
const owner=(p,m='GET',b)=>req(p,m,b,ownerHeaders());
async function device(){const c=await owner('/api/admin/helper/pairing','POST',{});assert.equal(c.status,201);const {pairingCode}=await c.json(),res=await req('/api/helper/pair','POST',{pairingCode,deviceName:'Fixture PC',version:'1.0.0'});assert.equal(res.status,201);return res.json();}
async function claim(d,extra={}){const res=await req('/api/helper/claim','POST',{version:'1.0.0',paused:false,modelStatus:'ready',...extra},bearer(d));assert.equal(res.status,200);return res.json();}
const upload=(d,j,b=png(),headers={})=>mf.dispatchFetch(origin+`/api/helper/jobs/${j.id}/result`,{method:'PUT',headers:{...bearer(d),'X-Job-Lease':j.leaseToken,'Content-Type':'image/png','Content-Length':String(b.length),...headers},body:b});
async function reset(){await db.batch(['DELETE FROM cms_thumbnail_jobs','DELETE FROM cms_helper_devices','DELETE FROM cms_helper_pairings','DELETE FROM cms_rate_limits','DELETE FROM cms_media','DELETE FROM cms_state','DELETE FROM cms_revisions'].map(s=>db.prepare(s)));const content=seed(),bytes=png({opaque:true});await bucket.put(`${mediaId}/original`,bytes);await bucket.put(`${mediaId}/preview`,bytes);await db.prepare(`INSERT INTO cms_media(id,filename,mime,size,preview_mime,preview_size,original_uploaded,preview_uploaded,is_published,created_at) VALUES (?,'fixture.png','image/png',?,'image/png',?,1,1,1,0)`).bind(mediaId,bytes.length,bytes.length).run();await db.prepare('INSERT INTO cms_state(id,draft_json,published_revision,published_json,updated_at) VALUES (1,?,0,?,0)').bind(JSON.stringify(content),JSON.stringify(content)).run();await db.prepare(`INSERT INTO cms_revisions(revision,content_json,action,created_at) VALUES (0,?,'save',0)`).bind(JSON.stringify(content)).run();}
const queue=()=>owner('/api/admin/content','PUT',{expectedRevision:0,content:seed()});
before(async()=>{const bundle=await build({entryPoints:[fileURLToPath(new URL('../src/index.ts',import.meta.url))],bundle:true,write:false,platform:'browser',format:'esm',external:['node:*'],logLevel:'silent'});mf=new Miniflare(convertV4MiniflareOptions({modules:true,compatibilityDate:'2026-10-01',compatibilityFlags:['nodejs_compat'],script:bundle.outputFiles[0].text,d1Databases:['DB'],r2Buckets:['MEDIA'],bindings:{OWNER_EMAIL:'owner@example.test',SITE_ORIGIN:origin,PAGES_ORIGIN:'https://pages.example.test',PROXY_ENABLED:'false'}}));db=await mf.getD1Database('DB');bucket=await mf.getR2Bucket('MEDIA');for(const file of ['0001_owner_cms.sql','0003_thumbnail_helper.sql']){const sql=(await readFile(new URL(`../migrations/${file}`,import.meta.url),'utf8')).replace(/^--.*$/gm,'');await db.batch(sql.split(';').filter(s=>s.trim()).map(s=>db.prepare(s)));}await db.prepare(`INSERT INTO cms_accounts(id,email,password_hash,created_at) VALUES (1,'owner@example.test','unused-fixture',0)`).run();await db.prepare('INSERT INTO cms_sessions(token_hash,account_id,csrf_token,expires_at,created_at) VALUES (?,1,?,?,0)').bind(hash(session),csrf,Math.floor(Date.now()/1000)+3600).run();});
after(async()=>{await mf?.dispose();});

test('migration is additive/idempotent and preserves owner content',async()=>{await reset();const sql=await readFile(new URL('../migrations/0003_thumbnail_helper.sql',import.meta.url),'utf8');assert.doesNotMatch(sql,/\b(?:ALTER|DROP|TRUNCATE)\b/i);const row=await db.prepare('SELECT * FROM cms_state').first();await db.batch(sql.replace(/^--.*$/gm,'').split(';').filter(s=>s.trim()).map(s=>db.prepare(s)));assert.deepEqual(await db.prepare('SELECT * FROM cms_state').first(),row);});
test('owner auth, origin and CSRF guard pairing before any body processing',async()=>{await reset();assert.equal((await req('/api/admin/helper/pairing','POST',{})).status,401);assert.equal((await req('/api/admin/helper/pairing','POST',{}, {...ownerHeaders(),Origin:'https://evil.test'})).status,403);assert.equal((await req('/api/admin/helper/pairing','POST',{}, {...ownerHeaders(),'X-CSRF-Token':'bad'})).status,403);assert.equal((await db.prepare('SELECT COUNT(*) count FROM cms_helper_pairings').first()).count,0);});
test('pairing codes expire, are one use, and only hashes persist',async()=>{await reset();const {pairingCode}=await (await owner('/api/admin/helper/pairing','POST',{})).json(),row=await db.prepare('SELECT * FROM cms_helper_pairings').first();assert.equal(row.code_hash,hash(pairingCode));assert.equal(row.expires_at-row.created_at,600);const res=await req('/api/helper/pair','POST',{pairingCode}),d=await res.json();assert.equal(res.status,201);assert.equal((await db.prepare('SELECT token_hash FROM cms_helper_devices').first()).token_hash,hash(d.token));assert.equal((await req('/api/helper/pair','POST',{pairingCode})).status,403);const expired=await (await owner('/api/admin/helper/pairing','POST',{})).json();await db.prepare('UPDATE cms_helper_pairings SET expires_at=0').run();assert.equal((await req('/api/helper/pair','POST',expired)).status,403);});
test('pairing and generation limits block guessing',async()=>{await reset();for(let i=0;i<8;i++)assert.equal((await req('/api/helper/pair','POST',{pairingCode:'0000000000'})).status,403);assert.equal((await req('/api/helper/pair','POST',{pairingCode:'0000000000'})).status,429);for(let i=0;i<6;i++)assert.equal((await owner('/api/admin/helper/pairing','POST',{})).status,201);assert.equal((await owner('/api/admin/helper/pairing','POST',{})).status,429);});
test('device bearer never authenticates owner APIs; owner cookies never authenticate helper',async()=>{await reset();const d=await device();assert.equal((await req('/api/admin/content','GET',undefined,bearer(d))).status,401);assert.equal((await req('/api/helper/claim','POST',{paused:false},ownerHeaders())).status,401);assert.equal((await req('/api/helper/claim','POST',{paused:false},{...bearer(d),Origin:origin})).status,403);});
test('save and publish dedupe an immutable input; preserve legacy static thumbnails',async()=>{await reset();assert.equal((await queue()).status,200);assert.equal((await owner('/api/admin/publish','POST',{expectedRevision:1})).status,200);const jobs=(await db.prepare('SELECT * FROM cms_thumbnail_jobs').all()).results;assert.equal(jobs.length,1);const source=Buffer.from(await (await bucket.get(`${mediaId}/preview`)).arrayBuffer());assert.equal(jobs[0].input_sha256,hash(source));assert.deepEqual(Buffer.from(await (await bucket.get(jobs[0].input_key)).arrayBuffer()),source);const doc=await (await req('/api/portfolio')).json();assert.equal(doc.projects[0].gridThumb,null);assert.equal(doc.projects[0].thumbnailStatus,'queued');assert.equal(doc.projects[1].thumbWebp,seed().projects[1].thumbWebp);assert.equal(doc.projects[1].thumbnailStatus,undefined);});
test('claims are atomic across devices; input requires exact device and lease',async()=>{await reset();await queue();const a=await device(),b=await device(),claims=await Promise.all([claim(a),claim(b)]);assert.equal(claims.filter(c=>c.job).length,1);const i=claims.findIndex(c=>c.job),d=[a,b][i],other=[a,b][1-i],j=claims[i].job;assert.equal((await claim(d)).job,null);assert.equal((await req(`/api/helper/jobs/${j.id}/input`)).status,401);assert.equal((await req(`/api/helper/jobs/${j.id}/input`,'GET',undefined,{...bearer(other),'X-Job-Lease':j.leaseToken})).status,409);const input=await req(`/api/helper/jobs/${j.id}/input`,'GET',undefined,{...bearer(d),'X-Job-Lease':j.leaseToken});assert.equal(input.status,200);assert.equal(hash(Buffer.from(await input.arrayBuffer())),j.inputSha256);});
test('missing/loading/failed model and local pause never lease, but record online status',async()=>{await reset();await queue();const d=await device();for(const state of ['missing','loading','failed'])assert.equal((await claim(d,{modelStatus:state})).job,null);assert.equal((await claim(d,{paused:true})).job,null);const info=await (await owner('/api/admin/helper')).json();assert.equal(info.devices[0].localPaused,true);assert.equal(info.devices[0].online,true);assert.equal(info.model.id,'birefnet-general-lite');assert.deepEqual(info.download,{ready:false,url:null,sha256:null,version:null,size:null,platform:'windows-amd64'});assert.ok((await claim(d)).job);});
test('remote pause is returned by heartbeat and prevents completion',async()=>{await reset();await queue();const d=await device(),j=(await claim(d)).job;assert.equal((await owner(`/api/admin/helper/devices/${d.deviceId}/pause`,'POST',{paused:true})).status,200);const res=await req(`/api/helper/jobs/${j.id}/heartbeat`,'POST',{leaseToken:j.leaseToken},bearer(d));assert.equal(res.status,200);assert.equal((await res.json()).paused,true);assert.equal((await upload(d,j)).status,409);});
test('expired offline leases recover; attempts are bounded and old tokens cannot complete',async()=>{await reset();await queue();const d=await device(),old=(await claim(d)).job;await db.prepare('UPDATE cms_thumbnail_jobs SET lease_expires_at=0').run();const fresh=(await claim(d)).job;assert.equal(fresh.id,old.id);assert.notEqual(fresh.leaseToken,old.leaseToken);assert.equal((await upload(d,old)).status,409);await db.prepare('UPDATE cms_thumbnail_jobs SET lease_expires_at=0,attempts=3').run();assert.equal((await claim(d)).job,null);assert.equal((await db.prepare('SELECT status FROM cms_thumbnail_jobs').first()).status,'failed');});
test('opaque RGBA, empty subject, corrupt CRC and decompression overflow are rejected',async()=>{await reset();await queue();const d=await device(),j=(await claim(d)).job;for(const b of [png({opaque:true}),png({empty:true}),png({expansion:true})])assert.equal((await upload(d,j,b)).status,422);const corrupt=png();corrupt[45]^=1;assert.equal((await upload(d,j,corrupt)).status,422);assert.equal((await upload(d,j,png(),{'Content-Type':'image/jpeg'})).status,415);assert.equal((await upload(d,j,Buffer.alloc(2*1024*1024+1))).status,413);await assert.rejects(upload(d,j,png(),{'Content-Length':String(png().length+1)}),error=>error.code==='UND_ERR_REQ_CONTENT_LENGTH_MISMATCH'||error.cause?.code==='UND_ERR_REQ_CONTENT_LENGTH_MISMATCH');assert.equal((await db.prepare('SELECT status FROM cms_thumbnail_jobs').first()).status,'working');});
test('transparent result changes only derived grid fields; no original/content/revision writes',async()=>{await reset();await queue();const d=await device(),j=(await claim(d)).job,state=await db.prepare('SELECT * FROM cms_state').first(),original=Buffer.from(await (await bucket.get(`${mediaId}/original`)).arrayBuffer());const res=await upload(d,j,png({filter:4}));assert.equal(res.status,200);assert.equal((await res.json()).status,'ready');assert.deepEqual(await db.prepare('SELECT * FROM cms_state').first(),state);assert.deepEqual(Buffer.from(await (await bucket.get(`${mediaId}/original`)).arrayBuffer()),original);const doc=await (await req('/api/portfolio')).json();assert.equal(doc.projects[0].gridThumb,`/helper-media/${j.id}.png`);for(const f of ['thumbWebp','full','heroWebp'])assert.equal(doc.projects[0][f],seed().projects[0][f]);assert.equal(doc.revision,0);assert.equal((await upload(d,j)).status,409);const image=await req(doc.projects[0].gridThumb);assert.equal(image.status,200);assert.equal(image.headers.get('Content-Type'),'image/png');assert.equal((await req(doc.projects[0].gridThumb,'HEAD')).status,200);assert.equal((await req(doc.projects[0].gridThumb,'GET',undefined,{'If-None-Match':image.headers.get('ETag')})).status,304);});
test('all five PNG filters decode and validate transparency',async()=>{await reset();await db.prepare('UPDATE cms_state SET published_json=NULL,published_revision=NULL').run();const d=await device();for(let filter=0;filter<5;filter++){const content=seed();content.projects[0].id=filter+10;content.projects[0].slug=`filter-${filter}`;assert.equal((await owner('/api/admin/content','PUT',{expectedRevision:filter,content})).status,200);const j=(await claim(d)).job;assert.equal((await upload(d,j,png({filter}))).status,200);}});
test('source fingerprint changes make completion stale without touching owner draft',async()=>{await reset();await queue();const d=await device(),j=(await claim(d)).job,content=seed();content.projects[0].thumbWebp='/assets/new-cover.webp';await db.prepare('UPDATE cms_state SET draft_json=?,published_json=?').bind(JSON.stringify(content),JSON.stringify(content)).run();const state=await db.prepare('SELECT * FROM cms_state').first(),res=await upload(d,j);assert.equal(res.status,200);assert.equal((await res.json()).status,'stale');assert.deepEqual(await db.prepare('SELECT * FROM cms_state').first(),state);const doc=await (await req('/api/portfolio')).json();assert.equal(doc.projects[0].gridThumb,undefined);assert.equal(doc.projects[0].thumbWebp,'/assets/new-cover.webp');assert.equal((await req(`/helper-media/${j.id}.png`)).status,404);});
test('device revocation denies input/result immediately and releases active lease',async()=>{await reset();await queue();const d=await device(),j=(await claim(d)).job;assert.equal((await owner(`/api/admin/helper/devices/${d.deviceId}/revoke`,'POST',{})).status,200);assert.equal((await req('/api/helper/claim','POST',{paused:false},bearer(d))).status,401);assert.equal((await upload(d,j)).status,401);assert.equal((await db.prepare('SELECT status FROM cms_thumbnail_jobs').first()).status,'queued');});
test('unsupported source is a visible failed state and cannot be blindly retried',async()=>{await reset();await db.prepare(`UPDATE cms_media SET preview_mime='image/avif'`).run();await queue();const d=await device();assert.equal((await claim(d)).job,null);const info=await (await owner('/api/admin/helper')).json();assert.equal(info.jobs[0].status,'failed');assert.equal(info.jobs[0].errorCode,'input_unsupported');assert.equal((await owner('/api/admin/helper/retry','POST',{jobId:info.jobs[0].id})).status,409);assert.equal((await (await req('/api/portfolio')).json()).projects[0].thumbnailStatus,'failed');});
test('download remains unavailable until a verified manifest matches exact hosted size',async()=>{await reset();assert.equal((await req('/downloads/ashvini-helper.exe')).status,404);const exe=Buffer.from('MZfixture verified binary bytes');await bucket.put('downloads/ashvini-helper.exe',exe);assert.equal((await req('/downloads/ashvini-helper.exe')).status,404);await bucket.put('downloads/helper-release.json',JSON.stringify({buildVerified:true,sha256:hash(exe),size:exe.length+1,version:'1.0.0'}));assert.equal((await req('/downloads/ashvini-helper.exe')).status,404);await bucket.put('downloads/helper-release.json',JSON.stringify({buildVerified:true,sha256:hash(exe),size:exe.length,version:'1.0.0'}));const info=await (await owner('/api/admin/helper')).json();assert.equal(info.download.ready,true);assert.equal(info.download.sha256,hash(exe));assert.equal(info.download.url,'/downloads/ashvini-helper.exe');const full=await req(info.download.url);assert.equal(full.status,200);assert.deepEqual(Buffer.from(await full.arrayBuffer()),exe);assert.equal((await req(info.download.url,'HEAD')).status,200);const part=await req(info.download.url,'GET',undefined,{Range:'bytes=0-1'});assert.equal(part.status,206);assert.equal(part.headers.get('Content-Range'),`bytes 0-1/${exe.length}`);assert.equal(await part.text(),'MZ');assert.equal((await req(info.download.url,'GET',undefined,{'If-None-Match':full.headers.get('ETag')})).status,304);await bucket.put('downloads/helper-release.json',JSON.stringify({buildVerified:false,sha256:hash(exe),size:exe.length,version:'1.0.0'}));assert.equal((await req(info.download.url)).status,404);});

test('rollback to a stale source reuses its immutable input and issues a fresh lease',async()=>{
 await reset();await queue();const d=await device(),old=(await claim(d)).job;
 const first=await db.prepare('SELECT * FROM cms_thumbnail_jobs WHERE id=?').bind(old.id).first(),input=Buffer.from(await (await bucket.get(first.input_key)).arrayBuffer());
 const changed=seed();changed.projects[0].thumbWebp='/assets/replacement-cover.webp';
 assert.equal((await owner('/api/admin/content','PUT',{expectedRevision:1,content:changed})).status,200);
 assert.equal((await owner('/api/admin/publish','POST',{expectedRevision:2})).status,200);
 const completion=await upload(d,old);assert.equal(completion.status,200);assert.equal((await completion.json()).status,'stale');
 assert.equal((await db.prepare('SELECT status FROM cms_thumbnail_jobs WHERE id=?').bind(old.id).first()).status,'stale');
 assert.equal((await owner('/api/admin/rollback','POST',{expectedRevision:2,revision:1})).status,200);
 const revived=await db.prepare('SELECT * FROM cms_thumbnail_jobs WHERE id=?').bind(old.id).first();
 assert.equal(revived.status,'queued');assert.equal(revived.attempts,0);for(const field of ['device_id','lease_hash','lease_expires_at','error_code'])assert.equal(revived[field],null);
 assert.equal(revived.input_key,first.input_key);assert.equal(revived.input_sha256,first.input_sha256);assert.deepEqual(Buffer.from(await (await bucket.get(revived.input_key)).arrayBuffer()),input);
 const fresh=(await claim(d)).job;assert.equal(fresh.id,old.id);assert.notEqual(fresh.leaseToken,old.leaseToken);assert.equal((await upload(d,old)).status,409);
 const state=await db.prepare('SELECT * FROM cms_state').first();assert.equal((await upload(d,fresh)).status,200);assert.deepEqual(await db.prepare('SELECT * FROM cms_state').first(),state);
 assert.equal((await (await req('/api/portfolio')).json()).projects[0].thumbWebp,'/assets/replacement-cover.webp');
});

test('large eligible backfills progress eight jobs per poll without duplicate or skipped sources',async()=>{
 await reset();const content=seed();content.projects=Array.from({length:21},(_,index)=>({...seed().projects[0],id:index+1,slug:`batch-project-${index+1}`}));
 await db.prepare('UPDATE cms_state SET draft_json=?,published_json=?').bind(JSON.stringify(content),JSON.stringify(content)).run();
 const state=await db.prepare('SELECT * FROM cms_state').first();
 for(const expected of [8,16,21,21]) {
  const response=await owner('/api/admin/helper');assert.equal(response.status,200);const info=await response.json();assert.equal(info.jobs.length,expected);
  const jobs=(await db.prepare('SELECT id,project_id,source_fingerprint,input_key FROM cms_thumbnail_jobs').all()).results;
  assert.equal(jobs.length,expected);assert.equal(new Set(jobs.map(job=>job.project_id)).size,expected);assert.equal(new Set(jobs.map(job=>job.source_fingerprint)).size,expected);assert.equal(new Set(jobs.map(job=>job.input_key)).size,expected);
 }
 const jobs=(await db.prepare('SELECT project_id FROM cms_thumbnail_jobs').all()).results;assert.deepEqual(jobs.map(job=>job.project_id).sort((a,b)=>a-b),Array.from({length:21},(_,index)=>index+1));
 assert.deepEqual(await db.prepare('SELECT * FROM cms_state').first(),state);
});
