import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { before,after,test } from "node:test";
import { Miniflare,convertV4MiniflareOptions } from "miniflare";

let mf,db,forwarded;
const content={schemaVersion:1,revision:7,profile:{name:"Owner <test>",homeDescription:"Published introduction",aboutTitle:"About me",aboutBio:"Published biography",seo:{home:{title:"Fresh home title",description:"Fresh description"}},faq:[{q:"A question?",a:"An answer."}]},projects:[{id:20,slug:"new-project",title:"New project",description:"New description",nsfw:false,order:1},{id:21,slug:"sensitive-project",title:"Sensitive title",description:"Private until consent",nsfw:true,order:2}],editorial:[],sketches:[]};
before(async()=>{
  mf=new Miniflare(convertV4MiniflareOptions({modules:true,compatibilityDate:"2026-10-01",compatibilityFlags:["nodejs_compat"],script:await readFile(new URL("../.build/index.js",import.meta.url),"utf8"),d1Databases:["DB"],r2Buckets:["MEDIA"],bindings:{OWNER_EMAIL:"owner@example.test",SITE_ORIGIN:"https://cms.test",PAGES_ORIGIN:"https://pages.example.test",PROXY_ENABLED:"true"},outboundService:async(request)=>{forwarded=request;return new Response('<!doctype html><html><head><title>Old title</title><meta name="description" content="Old description"><script type="application/ld+json">{"name":"old person"}</script><script type="module" src="/assets/app.js"></script></head><body><div id="root"><main class="seo-shell">Old content</main></div></body></html>',{status:new URL(request.url).pathname==="/index.html"?308:new URL(request.url).pathname.startsWith("/portfolio/")||new URL(request.url).pathname.startsWith("/admin")?404:200,headers:{"Content-Type":"text/html","Set-Cookie":"untrusted-pages-cookie=fixture",...(new URL(request.url).pathname==="/index.html"?{Location:"/"}:{})}});}}));
  db=await mf.getD1Database("DB");
  for(const file of ["0001_owner_cms.sql","0003_thumbnail_helper.sql"]){const schema=(await readFile(new URL(`../migrations/${file}`,import.meta.url),"utf8")).replace(/^--.*$/gm,"");await db.batch(schema.split(";").filter((sql)=>sql.trim()).map((sql)=>db.prepare(sql)));}
  await db.prepare("INSERT INTO cms_state(id,draft_revision,draft_json,published_revision,published_json,updated_at) VALUES (1,7,?,7,?,0)").bind(JSON.stringify(content),JSON.stringify(content)).run();
});
after(async()=>{await mf?.dispose();});
test("proxy preserves frontend assets and injects escaped non-executable JSON",async()=>{
  const res=await mf.dispatchFetch("https://cms.test/",{headers:{Cookie:"private-cookie",Authorization:"Bearer private-test","X-Setup-Token":"private-test","X-CSRF-Token":"private-test"}});const html=await res.text();assert.equal(res.status,200);assert.match(html,/src="\/assets\/app.js"/);assert.match(html,/<title>Fresh home title<\/title>/);assert.match(html,/Fresh description/);assert.match(html,/Published introduction/);assert.ok(!html.includes("Old content"));
  const match=/<script id="portfolio-content" type="application\/json">([^]*?)<\/script>/.exec(html);assert.ok(match);assert.ok(match[1].includes("\\u003c"));assert.equal(JSON.parse(match[1]).revision,7);
    assert.equal((html.match(/application\/ld\+json/g)||[]).length,1);assert.ok(!html.includes("old person"));assert.equal(forwarded.headers.get("Cookie"),null);assert.equal(forwarded.headers.get("Authorization"),null);assert.equal(forwarded.headers.get("X-Setup-Token"),null);assert.equal(res.headers.get("Set-Cookie"),null);
});
test("new CMS project paths receive successful crawlable HTML despite Pages 404",async()=>{const res=await mf.dispatchFetch("https://cms.test/portfolio/20");assert.equal(res.status,200);const html=await res.text();assert.match(html,/<h1>New project<\/h1>/);assert.match(html,/<title>New project — Owner &lt;test&gt;<\/title>/);});
test("missing projects preserve a 404 response",async()=>{assert.equal((await mf.dispatchFetch("https://cms.test/portfolio/999")).status,404);});
test("sensitive project HTML has a consent shell, safe OG and no public schema",async()=>{const res=await mf.dispatchFetch("https://cms.test/portfolio/21");const html=await res.text();assert.equal(res.headers.get("X-Robots-Tag"),"noindex,follow");assert.match(html,/<h1>Sensitive artwork<\/h1>/);assert.ok(!html.includes("application/ld+json"));assert.match(html,/social-preview.webp/);});
test("sitemap and llms derive published paths without fake lastmod or sensitive listings",async()=>{const sitemap=await(await mf.dispatchFetch("https://cms.test/sitemap.xml")).text();assert.ok(sitemap.includes("/portfolio/20"));assert.ok(!sitemap.includes("/portfolio/21"));assert.ok(!sitemap.includes("lastmod"));const llms=await(await mf.dispatchFetch("https://cms.test/llms.txt")).text();assert.ok(llms.includes("New project"));assert.ok(!llms.includes("Sensitive title"));});
test("about structured data follows the published questions",async()=>{const html=await(await mf.dispatchFetch("https://cms.test/about")).text();assert.match(html,/FAQPage/);assert.match(html,/A question\?/);assert.match(html,/Published biography/);});
test("admin GET and HEAD are non-indexable and cannot be framed",async()=>{for(const method of ["GET","HEAD"]){const res=await mf.dispatchFetch("https://cms.test/admin",{method});assert.equal(res.headers.get("X-Robots-Tag"),"noindex, nofollow, noarchive");assert.equal(res.headers.get("X-Frame-Options"),"DENY");assert.equal(res.headers.get("Content-Security-Policy"),"frame-ancestors 'none'");assert.equal(res.headers.get("Referrer-Policy"),"no-referrer");assert.equal(res.headers.get("Cache-Control"),"private, no-store");}});
test("direct editor routes load the SPA entry even when Pages has no admin file",async()=>{for(const method of ["GET","HEAD"]){const res=await mf.dispatchFetch("https://cms.test/admin/setup",{method});assert.equal(res.status,200);assert.equal(new URL(forwarded.url).pathname,"/");if(method==="GET"){const html=await res.text();assert.match(html,/<title>Portfolio editor/);assert.match(html,/<h1>Portfolio editor<\/h1>/);assert.ok(!html.includes("application/ld+json"));assert.ok(!html.includes('rel="canonical"'));}}});
test("scheme-relative request paths cannot override the fixed Pages origin",async()=>{const res=await mf.dispatchFetch("https://cms.test//outside.example/path");assert.equal(res.status,200);assert.equal(new URL(forwarded.url).origin,"https://pages.example.test");assert.equal(new URL(forwarded.url).pathname,"//outside.example/path");});
test("static asset passthrough preserves cache and avoids a snapshot query",async()=>{const isolated=new Miniflare(convertV4MiniflareOptions({modules:true,compatibilityDate:"2026-10-01",compatibilityFlags:["nodejs_compat"],script:await readFile(new URL("../.build/index.js",import.meta.url),"utf8"),d1Databases:["DB"],r2Buckets:["MEDIA"],bindings:{OWNER_EMAIL:"owner@example.test",SITE_ORIGIN:"https://cms.test",PAGES_ORIGIN:"https://pages.example.test",PROXY_ENABLED:"true"},outboundService:async()=>new Response("static fixture",{headers:{"Content-Type":"text/plain","Cache-Control":"public, max-age=300","ETag":"fixture"}})}));try{for(const path of ["/assets/app.js","/avatar.webp","/robots.txt"]){const res=await isolated.dispatchFetch("https://cms.test"+path);assert.equal(res.status,200);assert.equal(res.headers.get("Cache-Control"),"public, max-age=300");assert.equal(res.headers.get("ETag"),"fixture");assert.equal(await res.text(),"static fixture");}}finally{await isolated.dispose();}});
